default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: zaq12wsx
  pool: 5
  timeout: 5000
  host: localhost
development:
  <<: *default
  database: GSDatabase
test:
  <<: *default
  database: GSDatabaseTest
production:
  <<: *default
  database: GSDatabase